### ISSUE TITLE
S3 Storage Support

### ISSUE THREAD

**Issue by louissallee** [namumakwembo/wirechat#52]
### Package Version

v0.1.0

### Laravel Version

v11.9

### PHP Version

PHP 8.3.0

### Tailwind CSS Version

v3.4.16

### Problem description

When attachments are configured in the wirechat.php configuration file, if we specify an S3 disk in storage_disk, the files will be stored perfectly on the S3 bucket, but the URLs will not be generated correctly in Wirechat (/storage/path instead of the bucket URL).

It might be worthwhile correcting this point.

### Expected behavior

-

### Steps to reproduce

-

### Relevant log output

```shell

```

**Comment by namumakwembo** [comment]
Thanks for reporting this issue.. I'll look into it and work on a fix soon. 🚀

**Comment by namumakwembo** [comment]
fixed #58

**Comment by louissallee** [comment]
Hello,

Thanks for your response !

It seems to fix the URL generation issue when multiple local disks are used. However, the problem persists when using an S3-type disk (with a different base URL).

I used the chat to send an example.txt file. It is correctly stored on my S3 disk with the name DslcFkv7E9DBbqwehgGujm4gYZp5iwEYA0ZJlcXZ.txt. But in the database, you're storing the URL /storage/attachments/DslcFkv7E9DBbqwehgGujm4gYZp5iwEYA0ZJlcXZ.png, whereas the file is actually stored at /attachments/DslcFkv7E9DBbqwehgGujm4gYZp5iwEYA0ZJlcXZ.png on my S3 bucket. Most importantly, the URL shouldn't be application.com/storage/attachments/DslcFkv7E9DBbqwehgGujm4gYZp5iwEYA0ZJlcXZ.png but rather S3_URL/attachments/DslcFkv7E9DBbqwehgGujm4gYZp5iwEYA0ZJlcXZ.png.

In my case, the correct URL is : https://s3-service.tld/bucket-name/attachments/DslcFkv7E9DBbqwehgGujm4gYZp5iwEYA0ZJlcXZ.png.

I hope my explanation is clear enough.

**Comment by louissallee** [comment]
We also need to handle the fact that, by default, when a file is uploaded to S3 storage, it's set with private visibility, making it inaccessible via the URL. Therefore, the file should either be uploaded with public visibility or accessed via temporary URLs, though I think using temporary URLs might complicate things further.

**Comment by namumakwembo** [comment]
> Hello,
> 
> Thanks for your response !
> 
> It seems to fix the URL generation issue when multiple local disks are used. However, the problem persists when using an S3-type disk (with a different base URL).
> 
> I used the chat to send an example.txt file. It is correctly stored on my S3 disk with the name DslcFkv7E9DBbqwehgGujm4gYZp5iwEYA0ZJlcXZ.txt. But in the database, you're storing the URL /storage/attachments/DslcFkv7E9DBbqwehgGujm4gYZp5iwEYA0ZJlcXZ.png, whereas the file is actually stored at /attachments/DslcFkv7E9DBbqwehgGujm4gYZp5iwEYA0ZJlcXZ.png on my S3 bucket. Most importantly, the URL shouldn't be application.com/storage/attachments/DslcFkv7E9DBbqwehgGujm4gYZp5iwEYA0ZJlcXZ.png but rather S3_URL/attachments/DslcFkv7E9DBbqwehgGujm4gYZp5iwEYA0ZJlcXZ.png.
> 
> In my case, the correct URL is : https://s3-service.tld/bucket-name/attachments/DslcFkv7E9DBbqwehgGujm4gYZp5iwEYA0ZJlcXZ.png.
> 
> I hope my explanation is clear enough.

This new update should fix the issue of file or media not showing up in the chat because of them being stored on S3 bucket , can you please confirm that ?

**Comment by louissallee** [comment]
Actually, that's not the case.

I performed my tests right after downloading your update.

My file is stored in the DB as /storage/attachments/DslcFkv7E9DBbqwehgGujm4gYZp5iwEYA0ZJlcXZ.png instead of https://storage.hosting-provider.com/bucket-name/attachments/gfGdsaxqWCk4x9T3tUElR82c6eJXa6rLRoAO3e7q.png, and in the chat, the URL loaded is https://my-laravel-project.test/storage/attachments/DslcFkv7E9DBbqwehgGujm4gYZp5iwEYA0ZJlcXZ.png.

Knowing that my .env configuration is as follows:

S3_ACCESS_KEY_ID=[CONFIDENTIAL]
S3_SECRET_ACCESS_KEY=[CONFIDENTIAL]
S3_BUCKET=bucket-name
S3_DEFAULT_REGION=us-east-1
S3_USE_PATH_STYLE_ENDPOINT=true
S3_URL=https://storage.hosting-provider.com/bucket-name
S3_ENDPOINT=https://storage.hosting-provider.com/

**Comment by namumakwembo** [comment]
> Hello,
> 
> Thanks for your response !
> 
> It seems to fix the URL generation issue when multiple local disks are used. However, the problem persists when using an S3-type disk (with a different base URL).
> 
> I used the chat to send an example.txt file. It is correctly stored on my S3 disk with the name DslcFkv7E9DBbqwehgGujm4gYZp5iwEYA0ZJlcXZ.txt. But in the database, you're storing the URL /storage/attachments/DslcFkv7E9DBbqwehgGujm4gYZp5iwEYA0ZJlcXZ.png, whereas the file is actually stored at /attachments/DslcFkv7E9DBbqwehgGujm4gYZp5iwEYA0ZJlcXZ.png on my S3 bucket. Most importantly, the URL shouldn't be application.com/storage/attachments/DslcFkv7E9DBbqwehgGujm4gYZp5iwEYA0ZJlcXZ.png but rather S3_URL/attachments/DslcFkv7E9DBbqwehgGujm4gYZp5iwEYA0ZJlcXZ.png.
> 
> In my case, the correct URL is : https://s3-service.tld/bucket-name/attachments/DslcFkv7E9DBbqwehgGujm4gYZp5iwEYA0ZJlcXZ.png.
> 
> I hope my explanation is clear enough.


---

Here's what happens when storing `url` and `file_path`:  
```php
// Example path
$path = 'attachments/file.png';

->create([
    // ...
    'file_path' => $path,
    'url' => Storage::disk(config('wirechat.storage_disk'))->url($path), // Generating URL using the configured disk and file path
]);
```

By the way, in the latest update, the `url` attribute is now mutated to derive the correct URL based on the `file_path` and storage disk, instead of relying on the base application URL. This ensures compatibility with different storage options, such as an S3 bucket.

**Comment by namumakwembo** [comment]
> Actually, that's not the case.
> 
> I performed my tests right after downloading your update.
> 
> My file is stored in the DB as /storage/attachments/DslcFkv7E9DBbqwehgGujm4gYZp5iwEYA0ZJlcXZ.png instead of https://storage.hosting-provider.com/bucket-name/attachments/gfGdsaxqWCk4x9T3tUElR82c6eJXa6rLRoAO3e7q.png, and in the chat, the URL loaded is https://my-laravel-project.test/storage/attachments/DslcFkv7E9DBbqwehgGujm4gYZp5iwEYA0ZJlcXZ.png.
> 
> Knowing that my .env configuration is as follows:
> 
> S3_ACCESS_KEY_ID=[CONFIDENTIAL] S3_SECRET_ACCESS_KEY=[CONFIDENTIAL] S3_BUCKET=bucket-name S3_DEFAULT_REGION=us-east-1 S3_USE_PATH_STYLE_ENDPOINT=true S3_URL=https://storage.hosting-provider.com/bucket-name S3_ENDPOINT=https://storage.hosting-provider.com/

I see. I think the issue might be with this part:  

```php
// Example: Displaying an image  
$path = 'attachments/file.png';  
$url = Storage::disk(config('wirechat.storage_disk'))->url($path);  

<img src="{{$url}}" ... />
```  

It seems that `->url()` might be resolving the URL based on the base application URL instead of the S3 disk configuration. Since I don’t have an S3 bucket to test this extensively, could you share how you're storing the file on S3? That way, I can better understand the setup and help find a way to generate the correct URL. Let me know what you find!

**Comment by louissallee** [comment]
I just sent you a Twitter DM with a bucket so you can perform your tests, along with my filesystems.php configuration. It will be easier this way :)

**Comment by namumakwembo** [comment]
Thanks! I'll check it out and get back to you.

**Comment by namumakwembo** [comment]
I pushed  a new tag , can you please test to check if the issue persists ?

**Comment by louissallee** [comment]
Everything's working ! Thanks !
